CREATE TABLE SERVICEIT.CATEGORY (
  ID_CATEGORY smallint(6) NOT NULL,
  NAMA_CATEGORY varchar(255) NOT NULL
);

-- Menambahkan foreign key ID_CATEGORY pada tabel SUPPLY
ALTER TABLE SUPPLY ADD FOREIGN KEY (ID_CATEGORY) REFERENCES SERVICEIT.CATEGORY(ID_CATEGORY);
